name: Generate Snake Contribution Grid

on:
  workflow_dispatch:  # Allows manual run
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ⬅️ VERY IMPORTANT! Allows pushing to `output` branch

    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: jonathan-thoms
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
